# INICIAR SESIÓN ECOAPRENDIZ
POST http://172.31.44.180:5000/inicio_sesion_routes/iniciarSesionEcoaprendiz
Content-Type: application/json

{
    "email": "isabel.seminario@gmail.com",
    "contrasena": "isabel123"
}
#####

# INICIAR SESIÓN ALIADO VERDE
POST http://172.31.44.180:5000/inicio_sesion_routes/iniciarSesionAliadoVerde
Content-Type: application/json

{
    "email": "plastitic@hotmail.com",
    "contrasena": "plastitic123"
}
#####