# INICIAR SESIÓN ECOAPRENDIZ
POST http://172.31.44.180:5000/inicio_sesion/iniciarSesionEcoaprendiz
Content-Type: application/json

{
    "email": "",
    "contrasena": ""
}
#####

# INICIAR SESIÓN ALIADO VERDE
POST http://172.31.44.180:5000/inicio_sesion/iniciarSesionAliadoVerde
Content-Type: application/json

{
    "email": "",
    "contrasena": ""
}
#####